// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArMxrrtKN1N2qraRngQ3qepaQSI47_KR0',
    appId: '1:176632001268:web:db9ad6c0c8144338aea4a1',
    messagingSenderId: '176632001268',
    projectId: 'todo-f23ab',
    authDomain: 'todo-f23ab.firebaseapp.com',
    storageBucket: 'todo-f23ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmERmn_l27jWQOJcn4ggRee8RVv47FwFk',
    appId: '1:176632001268:android:789fc9f39a08e664aea4a1',
    messagingSenderId: '176632001268',
    projectId: 'todo-f23ab',
    storageBucket: 'todo-f23ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArMxrrtKN1N2qraRngQ3qepaQSI47_KR0',
    appId: '1:176632001268:web:11cc5db295f79a54aea4a1',
    messagingSenderId: '176632001268',
    projectId: 'todo-f23ab',
    authDomain: 'todo-f23ab.firebaseapp.com',
    storageBucket: 'todo-f23ab.firebasestorage.app',
  );
}
